---
services:
  starter:
    git_url: http://github.com/cloud66/starter.git
    git_branch: master
    use_habitus: true
    use_habitus_step: runtime
    ports:
    - container: 9090
      http: 80
      https: 443
  